`StandardScaler: `

Scales features to have a mean of 0 and a standard deviation of 1. It subtracts the mean and divides by the standard deviation.

`initialization:`

+ import the 'StandardScaler' class from Scikit-leran.
+ Create an instance of 'StandardScaler'

In [1]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler = StandardScaler()

`Fitting`

+ Fit the scaler to the training data to compute the mean and standard deviation of each

+ Fit the scaler to the training data

scaler.fit(X_train)

`Transformation`

+ Transform the training and testing data using the fitted scaler to standardize the feature.

In [2]:
# Transform the training and testing data

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

NameError: name 'X_train' is not defined

# `Example 1:`


In [ ]:
from sklearn.preprocessing import StandardScaler
from  sklearn.model_selection import train_test_split
import numpy as np


# Example data
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

y = np.array([0,1,0])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2,random_state=42)

# Create a standardScaler instance
scaler = StandardScaler()

# Fit the scaler to the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


print("Training data")
print(X_train)
print("\nTesting data")
print(X_test)

print("     \n")


print("Scaled training data:")
print(X_test_scaled)
print("\nScaled testing data:")
print(X_test_scaled)

Training data
[[3 4]
 [5 6]]

Testing data
[[1 2]]
     

Scaled training data:
[[-3. -3.]]

Scaled testing data:
[[-3. -3.]]


# Ex 2

In [ ]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler

# Load the wine dataset
wine_data = load_wine()
X, y = wine_data.data, wine_data.target

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the features
X_standardized = scaler.fit_transform(X)

# Print the standardized features
print("Standardized Features:")
print(X_standardized)


Standardized Features:
[[ 1.51861254 -0.5622498   0.23205254 ...  0.36217728  1.84791957
   1.01300893]
 [ 0.24628963 -0.49941338 -0.82799632 ...  0.40605066  1.1134493
   0.96524152]
 [ 0.19687903  0.02123125  1.10933436 ...  0.31830389  0.78858745
   1.39514818]
 ...
 [ 0.33275817  1.74474449 -0.38935541 ... -1.61212515 -1.48544548
   0.28057537]
 [ 0.20923168  0.22769377  0.01273209 ... -1.56825176 -1.40069891
   0.29649784]
 [ 1.39508604  1.58316512  1.36520822 ... -1.52437837 -1.42894777
  -0.59516041]]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Custom array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the data
data_standardized = scaler.fit_transform(data)

# Print the standardized data
print("Standardized Data:")
print(data_standardized)


Standardized Data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [ ]:
from sklearn.preprocessing import StandardScaler

x = [1 , 45, 56 , 345, 456, 233, 1000]

